name: Build and Deploy Catalog from Tag

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  catalog:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2        
      - name: Set versions
        run: |
          export C_VERSION="${GITHUB_REF_NAME#v}" 
          export C_REVISION="${GITHUB_SHA}" 
          
          echo "CONNECTORS_VERSION=${C_VERSION}" >> $GITHUB_ENV
          echo "CONNECTORS_REVISION=${C_REVISION}" >> $GITHUB_ENV
          echo "CONNECTORS_RELEASE=${C_VERSION}-${C_REVISION}" >> $GITHUB_ENV

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_MCI_USR }}
          password: ${{ secrets.QUAY_MCI_PWD }}

      - name: Build Catalog Image
        run: |
          docker build \ 
            -t "quay.io/rhoas/cos-fleet-catalog-debezium:${CONNECTORS_RELEASE}" \
            -t "quay.io/rhoas/cos-fleet-catalog-debezium:latest" \
            -f Dockerfile.catalog .

      - name: Push Container Images
        run: |
          docker push "quay.io/rhoas/cos-fleet-catalog-debezium:${CONNECTORS_RELEASE}"
          docker push "quay.io/rhoas/cos-fleet-catalog-debezium:latest"


      - name: "Create Release Branch for tag {{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: release-${{ env.CONNECTORS_RELEASE }}
        run: |
          echo ""
          echo "tag     : ${{ github.ref_name }}"
          echo "release : ${CONNECTORS_RELEASE}"
          echo "branch  : ${BRANCH_NAME}"
          echo ""

          git config user.email "mas-connectors@redhat.com" 
          git config user.name "mas-connectors"

          git checkout -b "${BRANCH_NAME}"
          git add .
          git commit -am "Create release branch for tag ${{ github.ref_name }}"
          git reset --hard
          git push -u origin "${BRANCH_NAME}"

  update-manifest:
    needs:
      - catalog
    uses: ./.github/workflows/update-manifest.yml
    with:
      overlay: "staging"
    secrets:
      token: ${{ secrets.PR_TOKEN }}
